# Generated by Django 4.1.7 on 2023-03-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post_counts',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
